MarvelAPI-master/MarvelAPI.Sample/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using DBMarvelContext;
using MarvelAPI.Sample.Models;

namespace MarvelAPI.Sample.Controllers
{
    public class BranchController : Controller
    {

        #region Variables
       
        /// <summary>
        /// Serializador para JSON
        /// </summary>
        JavaScriptSerializer clsJson = new JavaScriptSerializer();

        

        /// <summary>
        /// Variable que almacena cadenas JSON
        /// </summary>
        string json;

        #endregion

        #region View
        public ActionResult Index()
        {
            return View();
        }
        #endregion


        #region Get
        [HttpPost]
        public string getBranchs()
        {
            try
            {
                Repository _repo = new Repository();
                List<Sucursales> _list = _repo.GetSucursales();

                var result = _list.Select(x => new SucursalesModel
                {
                    IdSucursal = x.IdSucursal,
                    Nombre = x.Nombre,
                    Ubicacion = x.Ubicacion,
                    Telefonos = x.Telefonos,
                    IdUsuarioAlta = x.IdUsuarioAlta,
                    FCreacion = String.Format(x.FCreacion.ToString(), "dd/mm/aaaa"),
                    FModificacion = String.Format(x.FModificacion.ToString(), "dd/mm/aaaa"),
                    Activo = x.Activo
                });
                return json = clsJson.Serialize(result.ToList());
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        [HttpPost]
        public string getBranchById(int Id)
        {
            try
            {
                Repository _repo = new Repository();
                List<Sucursales> _list = _repo.GetSucursalById(Id);

                var result = _list.Select(x => new SucursalesModel
                {
                    IdSucursal = x.IdSucursal,
                    Nombre = x.Nombre,
                    Ubicacion = x.Ubicacion,
                    Telefonos = x.Telefonos,
                    IdUsuarioAlta = x.IdUsuarioAlta,
                    FCreacion = String.Format(x.FCreacion.ToString(), "dd/mm/aaaa"),
                    FModificacion = String.Format(x.FModificacion.ToString(), "dd/mm/aaaa"),
                    Activo = x.Activo
                });
                return json = clsJson.Serialize(result.ToList());
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
        #endregion


        #region Update
        [HttpPost]
        public string updateBranch(int Id, string Nombre, string Ubicacion, string Telefonos)
        {
            string _resultRejection = "0";
            try
            {
                Repository _repo = new Repository();
                _resultRejection = Convert.ToString(_repo.UpdateSucursal(Id, Nombre, Ubicacion, Telefonos));
            }
            catch
            {
                _resultRejection = "0";
            }
            return clsJson.Serialize(_resultRejection);
        }
        #endregion

        #region Delete
        [HttpPost]
        public string deleteBranch(int Id)
        {
            string _resultRejection = "0";
            try
            {
                Repository _repo = new Repository();
                _resultRejection = Convert.ToString(_repo.DeleteSucursal(Id));
            }
            catch
            {
                _resultRejection = "0";
            }
            return clsJson.Serialize(_resultRejection);
        }
        #endregion

        #region Add
        [HttpPost]
        public string addBranch(string Nombre, string Ubicacion, string Telefonos)
        {
            string _resultRejection = "0";
            try
            {
                Repository _repo = new Repository();
                _resultRejection = Convert.ToString(_repo.AddSucursal(Nombre, Ubicacion, Telefonos));
            }
            catch
            {
                _resultRejection = "0";
            }
            return clsJson.Serialize(_resultRejection);
        }
        #endregion
    }
}

MarvelAPI-master/MarvelAPI.Sample/Controllers/ComicsStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using DBMarvelContext;
using MarvelAPI.Sample.Models;

namespace MarvelAPI.Sample.Controllers
{
    public class ComicsStoreController : Controller
    {
        #region Variables

        /// <summary>
        /// Serializador para JSON
        /// </summary>
        JavaScriptSerializer clsJson = new JavaScriptSerializer();



        /// <summary>
        /// Variable que almacena cadenas JSON
        /// </summary>
        string json;

        #endregion

        #region View
        // GET: ComicsStore
        public ActionResult Index()
        {
            return View();
        }

        #endregion


        #region Get
        [HttpPost]
        public string getComicsForBranc()
        {
            try
            {
                Repository _repo = new Repository();

                
                APIController _api = new APIController();
                GetComicsViewModel _getComicsViewModel = new GetComicsViewModel();
                _getComicsViewModel.Format = ComicFormat.Comic;
                _getComicsViewModel.FormatType = ComicFormatType.Comic;
                _getComicsViewModel.Limit = 10;

                var  _request = _api.Comics(_getComicsViewModel);
                
                var _seria = clsJson.Serialize(_request);
                var _root = clsJson.Deserialize<RootObject>(_seria);
              
                List<ComicsStore> _list =  _repo.GetComicsStore();

                List<ComicsStoreModel> _lstComicsModel = new List<ComicsStoreModel>();

                foreach (var _item in _list)
                {
                    int _codigo = Convert.ToInt32(_item.Codigo);
                    var _search = _root.Data.Where(x => x.Id == _codigo).FirstOrDefault();

                    if (_search != null)
                    {
                        ComicsStoreModel _itemComicModel = new ComicsStoreModel();
                        _itemComicModel.Check = false;
                        _itemComicModel.IdProducto = _item.IdProducto;
                        _itemComicModel.Codigo = _codigo;
                        _itemComicModel.IdInventario = _item.IdInventario;
                        _itemComicModel.NombreInventario = _item.NombreInventario;
                        _itemComicModel.IdSucursal = _item.IdSucursal;
                        _itemComicModel.NombreSucursal = _item.NombreSucursal;
                        _itemComicModel.Ubicacion = _item.Ubicacion;
                        _itemComicModel.TituloComic = _search.Title;
                        _itemComicModel.Formato = _search.Format;
                        _itemComicModel.NumPaginas = _search.PageCount;
                        _lstComicsModel.Add(_itemComicModel);
                    }
                }

               
                return json = clsJson.Serialize(_lstComicsModel.OrderBy(x => x.TituloComic));
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }

    #endregion
}

MarvelAPI-master/MarvelAPI.Sample/Controllers/ListComicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using DBMarvelContext;
using MarvelAPI.Sample.Models;

namespace MarvelAPI.Sample.Controllers
{

    public class ListComicsController : Controller
    {
        #region Variables

        /// <summary>
        /// Serializador para JSON
        /// </summary>
        JavaScriptSerializer clsJson = new JavaScriptSerializer();



        /// <summary>
        /// Variable que almacena cadenas JSON
        /// </summary>
        string json;

        #endregion

        #region View
        // GET: ListComics
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region Get
        [HttpPost]
        public string getListComics()
        {
            try
            {
                
                APIController _api = new APIController();
                GetComicsViewModel _getComicsViewModel = new GetComicsViewModel();
                _getComicsViewModel.Format = ComicFormat.Comic;
                _getComicsViewModel.FormatType = ComicFormatType.Comic;
                _getComicsViewModel.Limit = 100;

                var _request = _api.Comics(_getComicsViewModel);

                var _seria = clsJson.Serialize(_request);
                var _root = clsJson.Deserialize<RootObject>(_seria);

                List<ListComicsModel> _lstComicsModel = new List<ListComicsModel>();
                
                foreach (var _item in _root.Data)
                {
                    string _ima = (_item.Images.FirstOrDefault() != null) ? _item.Images.FirstOrDefault().Path + '.' + _item.Images.FirstOrDefault().Extension : "";
                    if(string.IsNullOrEmpty( _ima))
                    {
                        _ima = "Default";
                    }

                    string _fLan = (_item.Dates.Where(x => x.Type == "onsaleDate").FirstOrDefault() != null) ? _item.Dates.Where(x => x.Type == "onsaleDate").FirstOrDefault().Date2.ToString() :"";
                    if (string.IsNullOrEmpty(_fLan))
                    {
                        _fLan = "";
                    }
                    else
                    {
                        _fLan = System.Convert.ToDateTime(_fLan).ToString();
                    }

                    ListComicsModel _itemComicModel = new ListComicsModel();
                    _itemComicModel.Id = _item.Id;
                    _itemComicModel.Imagen = _ima;
                    _itemComicModel.Nombre = _item.Title;
                    _itemComicModel.Volumen = _item.IssueNumber.ToString();
                    _itemComicModel.FechaLanzamiento = _fLan;
                    _itemComicModel.Paginas = _item.PageCount;
                    _itemComicModel.Descripcion = _item.Description;
                    _lstComicsModel.Add(_itemComicModel);

                    
                }


                return json = clsJson.Serialize(_lstComicsModel.OrderBy(x => x.Nombre));
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        [HttpPost]
        public string getListCharacterByIds(List<int> Ids)
        {
            try
            {
                List<CharacterDetailModel> _lstCharacterDetailModel = new List<CharacterDetailModel>();

                foreach (int _id in Ids)
                {
                    APIController _api = new APIController();
                    var _request = _api.Characters(_id);
                    var _seria = clsJson.Serialize(_request);
                    var _root = clsJson.Deserialize<CharacterModel>(_seria);

                    string _ima = (_root.Data.Thumbnail != null) ? _root.Data.Thumbnail.Path + '.' + _root.Data.Thumbnail.Extension : "";
                    if (string.IsNullOrEmpty(_ima))
                    {
                        _ima = "Default";
                    }

                    CharacterDetailModel _detail = new CharacterDetailModel();
                    _detail.Name = _root.Data.Name;
                    _detail.Image = _ima;
                    _lstCharacterDetailModel.Add(_detail);
                }
                return json = clsJson.Serialize(_lstCharacterDetailModel);
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        [HttpPost]
        public string getListComicsById(int Id)
        {
            try
            {

                APIController _api = new APIController();
                var _request = _api.Comic(Id);

                var _seria = clsJson.Serialize(_request);
                var _root = clsJson.Deserialize<RootObject2>(_seria);

                List<ListComicsDetailModel> _lstComicsModel = new List<ListComicsDetailModel>();

                
                string _ima = (_root.Data.Images.FirstOrDefault() != null) ? _root.Data.Images.FirstOrDefault().Path + '.' + _root.Data.Images.FirstOrDefault().Extension : "";
                if (string.IsNullOrEmpty(_ima))
                {
                   _ima = "Default";
                }
                
                string _fLan = (_root.Data.Dates.Where(x => x.Type == "onsaleDate").FirstOrDefault() != null) ? _root.Data.Dates.Where(x => x.Type == "onsaleDate").FirstOrDefault().Date.ToString() : "";
                if (string.IsNullOrEmpty(_fLan))
                {
                  _fLan = "";
                }
                else
                {
                  _fLan = System.Convert.ToDateTime(_fLan).ToString();
                }

                ListComicsDetailModel _itemComicModel = new ListComicsDetailModel();
                _itemComicModel.Id = _root.Data.Id;
                _itemComicModel.Imagen = _ima;
                _itemComicModel.Nombre = _root.Data.Title;
                _itemComicModel.Volumen = _root.Data.IssueNumber.ToString();
                _itemComicModel.FechaLanzamiento = _fLan;
                _itemComicModel.Paginas = _root.Data.PageCount;
                _itemComicModel.Descripcion = _root.Data.Description;
                _itemComicModel.CountCharacter = _root.Data.Characters.Available;

                if (_itemComicModel.CountCharacter > 0)
                {
                    List<int> _lstNew = new List<int>();
                    foreach (var _item in _root.Data.Characters.Items)
                    {
                        int _IdCharacter = 0;
                        string[] _vec = _item.ResourceURI.Split('/');
                        
                        try
                        {
                            _IdCharacter = Convert.ToInt32(_vec[_vec.Length - 1]);
                            _lstNew.Add(_IdCharacter);
                        }
                        catch {}
                    }
                    _itemComicModel.LstCharacterId = _lstNew;
                }
                else
                {
                    _itemComicModel.LstCharacterId = null;
                }

                _lstComicsModel.Add(_itemComicModel);

                return json = clsJson.Serialize(_lstComicsModel.OrderBy(x => x.Nombre));
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        [HttpPost]
        public string getComicsExistBranch(int codigo)
        {
            string _sucursal = "";
            try
            {
                Repository _repo = new Repository();

                List<ComicsStore> _list = _repo.GetComicsStoreById(codigo.ToString());

                if (_list != null && _list.Count > 0)
                    _sucursal = _list.FirstOrDefault().NombreSucursal;
                else
                    _sucursal = "No Disponible";
                
            }
            catch (Exception)
            {
                _sucursal = "No Disponible";
            }

            return json = clsJson.Serialize(_sucursal);
        }
    }

    #endregion
}

MarvelAPI-master/MarvelAPI.Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Bit Technologies - Marvel API" />
    <title>MarvelAPI - @ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" media="screen" href="/css/stylesheet.css" />


    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Content/General.js"></script>
    <script src="~/Content/js/jquery-1.11.2.js"></script>
    <script src="~/Scripts/jquery-2.0.3.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/css/font-awesome.css" rel="stylesheet" />

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />


    <link href="~/Content/css/General.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/js/jquery.validate.js"></script>

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">



            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">Menu</a>
                    </div>
                    <ul class="nav navbar-nav">
                        @*<li class="active">*@
                        <li>
                            <a href="@Url.Action("Index", "Home")" class="elements">
                                <span>Pagina Principal</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Branch")" class="elements">
                                <span>Sucursales</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "ComicsStore")" class="elements">
                                <span>Comics por Tienda</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "ListComics")" class="elements">
                                <span>Listado de Comics</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>

            <h1 id="project_title" style="color: red;">Bit Technologies</h1>
            <h1 id="project_tagline" style="color: white;">Marvel API</h1>


        </header>
    </div>
    <!-- MAIN CONTENT -->
    <div id="main_content_wrap" class="outer">
        <section id="main_content" class="inner">
            @RenderBody()
        </section>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/ember")
    @RenderSection("scripts", required: false)


    <!-- Modal cargando-->
    <div class="modal fade" id="mdlCargando" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Mensajes</h4>
                </div>
                <div class="modal-body">
                    <h4>Cargando...</h4>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal cargando-->
    <!-- Modal mensaje-->
    <div class="modal fade" id="mdlMensaje" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="overflow:auto;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Mensajes</h4>
                </div>
                <div class="modal-body">
                    <h4 id="txtMensaje"></h4>
                </div>
            </div>
        </div>
    </div>
</body>
</html>